[package]
name = "mdbook-trunk"
description = "mdBook plugin which bundles packages using Trunk and includes them as iframes."
homepage = "https://mdbook-plugins.rustforweb.org/trunk.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
cargo = { version = "0.94.0", features = ["all-static"] }
clap.workspace = true
env_logger.workspace = true
fs_extra = "1.3.0"
html_parser = "0.7.0"
htmlentity = "1.3.2"
log.workspace = true
mdbook-core.workspace = true
mdbook-driver.workspace = true
mdbook-plugin-utils = { path = "../mdbook-plugin-utils", version = "0.3.0" }
mdbook-preprocessor.workspace = true
mdbook-renderer.workspace = true
peekread = "0.1.1"
pulldown-cmark.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
toml = "1.0.0"
